version: "3"
services: 
  app:
    container_name: zoom_app
    restart: always
    build: .
    ports:
      - 3001:3000
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27018:27017